### ISSUE TITLE
Week 3 suggested format.

### ISSUE THREAD

**Issue by willdkreid** [rasanderson/NES2303_Practical3#1]
We discussed whether to start the multiple explanatories section with an ANCOVA and then move onto two-way ANOVA with interactions.

The section I wrote for ANCOVA for our students last year can be found here: https://naturalandenvironmentalscience.shinyapps.io/MST2204_other_tests/#section-one-way-anova-two-way-anova-ancova

I think what would be good be to start this section with the ANCOVA and looking at parallel lines, then move onto interaction with lines that are not parallel, then onto two-way ANOVA with interaction. Then have quadratic fits as an oddity.

I do wonder whether the experimental design stuff needs (randomisation and blocking) should be a separate set of interactive webpages. It would then mean 3 interactive webpages for them to go through:
1. multiple explanatories
2. Anova: how does it work and how should I use it?
3. Improving exerimental design - randomisation, pseudoreplication and blocking and reminder on balanced v unbalanced designs

I don't think this will increase their workload because there will only be two extra subsects for them to go through but it might be a more logical order for them to understand.

Practical would then focus on ANCOVA and two-way ANOVA.

**Comment by rasanderson** [comment]
OK - I think (!) I've done as suggested. Quite a lot of cutting and pasting, and a new interactive website for randomised block design created.
